env:
  es2020: true # tracks tsconfig lib & target

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:markdown/recommended
  - prettier # last in order to override other configs

overrides:
  - files: ["*.ts"]
    extends:
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:import/typescript
    plugins:
      - "@typescript-eslint/eslint-plugin"

parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: "module"
settings:
  import/resolver:
    typescript: true
