env:
  es2020: true # tracks tsconfig lib & target
  node: true

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:markdown/recommended
  - prettier # last in order to override other configs

overrides:
  - files: ["*.ts"]
    extends:
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:import/typescript
    plugins:
      - "@typescript-eslint/eslint-plugin"
    rules:
      "@typescript-eslint/no-explicit-any": "warn"
  - files: ["**/*.md/*.js"]
    rules:
      "import/default": "off"
      "import/namespace": "off"
      "import/no-duplicates": "off"
      "import/no-named-as-default": "off"
      "import/no-named-as-default-member": "off"
      "import/no-unresolved": "off"

parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: "module"
settings:
  import/resolver:
    typescript: true

reportUnusedDisableDirectives: true
