compressionLevel: mixed

enableGlobalCache: false

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
    - win32
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl

yarnPath: .yarn/releases/yarn-4.0.1.cjs
