name: "Continuous Integration"

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn build
      - name: Cache build artifacts
        uses: actions/cache@v3
        id: build-cache
        with:
          key: build-${{ github.ref_name }}-${{ hashFiles('./packages/*/*.tsbuildinfo') }}
          path: |
            ./packages/*/dist
            ./packages/*/*.tsbuildinfo

  lint-eslint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Restore Build cache
        id: cache-build-restore
        uses: actions/cache/restore@v3
        with:
          key: build-${{ github.ref_name }}-${{ hashFiles('./packages/*/*.tsbuildinfo') }}
          restore-keys: |
            build-${{ github.ref_name }}-
            build-${{ github.head_ref }}-
            build-main
          path: |
            ./packages/*/dist
            ./packages/*/*.tsbuildinfo
      - run: yarn lint

  lint-prettier:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Restore Build cache
        id: cache-build-restore
        uses: actions/cache/restore@v3
        with:
          key: build-${{ github.ref_name }}-${{ hashFiles('./packages/*/*.tsbuildinfo') }}
          restore-keys: |
            build-${{ github.ref_name }}-
            build-${{ github.head_ref }}-
            build-main
          path: |
            ./packages/*/dist
            ./packages/*/*.tsbuildinfo
      - run: yarn format:ci
