name: "Continuous Integration"

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x, 20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn build
      - name: Cache build artifacts
        uses: actions/cache@v3
        id: build-cache
        with:
          key: ${{ runner.os }}-build-${{ github.ref_name }}-${{ hashFiles('./packages/*/*.tsbuildinfo') }}
          path: |
            ./packages/*/dist
            ./packages/*/*.tsbuildinfo

  lint-eslint:
    needs: build
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Restore Build cache
        id: cache-build-restore
        uses: actions/cache/restore@v3
        with:
          key: ${{ runner.os }}-build-${{ github.ref_name }}-${{ hashFiles('./packages/*/*.tsbuildinfo') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.ref_name }}-
            ${{ runner.os }}-build-${{ github.head_ref }}-
            ${{ runner.os }}-build-main
          path: |
            ./packages/*/dist
            ./packages/*/*.tsbuildinfo
      - run: yarn lint

  lint-prettier:
    needs: build
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Restore Build cache
        id: cache-build-restore
        uses: actions/cache/restore@v3
        with:
          key: ${{ runner.os }}-build-${{ github.ref_name }}-${{ hashFiles('./packages/*/*.tsbuildinfo') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.ref_name }}-
            ${{ runner.os }}-build-${{ github.head_ref }}-
            ${{ runner.os }}-build-main
          path: |
            ./packages/*/dist
            ./packages/*/*.tsbuildinfo
      - run: yarn format:ci

  test-unit:
    needs: build
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x, 20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Restore Build cache
        id: cache-build-restore
        uses: actions/cache/restore@v3
        with:
          key: ${{ runner.os }}-build-${{ github.ref_name }}-${{ hashFiles('./packages/*/*.tsbuildinfo') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.ref_name }}-
            ${{ runner.os }}-build-${{ github.head_ref }}-
            ${{ runner.os }}-build-main
          path: |
            ./packages/*/dist
            ./packages/*/*.tsbuildinfo
      - run: yarn test
