name: "Continuous Integration"

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          cache: "yarn"
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn dedupe --check

  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install --immutable
      - name: Cache yarn unplugged packages
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        id: yarn-unplugged-package-cache
        with:
          key: ${{ runner.os }}-yarn-unplugged-${{ github.ref_name }}-${{ hashFiles('yarn.lock') }}
          path: |
            ./.yarn/unplugged
      - run: yarn build
      - name: Cache build artifacts
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        id: build-cache
        with:
          key: ${{ runner.os }}-build-${{ github.ref_name }}-${{ hashFiles('./packages/*/*.tsbuildinfo') }}
          path: |
            ./packages/*/dist
            ./packages/*/*.tsbuildinfo

  lint-eslint:
    needs: build
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Restore Build cache
        id: cache-build-restore
        uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          key: ${{ runner.os }}-build-${{ github.ref_name }}-${{ hashFiles('./packages/*/*.tsbuildinfo') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.ref_name }}-
            ${{ runner.os }}-build-${{ github.head_ref }}-
            ${{ runner.os }}-build-main
          path: |
            ./packages/*/dist
            ./packages/*/*.tsbuildinfo
      - run: yarn lint:code

  lint-commit:
    needs: build
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Restore Build cache
        id: cache-build-restore
        uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          key: ${{ runner.os }}-build-${{ github.ref_name }}-${{ hashFiles('./packages/*/*.tsbuildinfo') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.ref_name }}-
            ${{ runner.os }}-build-${{ github.head_ref }}-
            ${{ runner.os }}-build-main
          path: |
            ./packages/*/dist
            ./packages/*/*.tsbuildinfo
      - run: yarn lint:commit --from=origin/${{ github.base_ref }} --to=origin/${{ github.head_ref }}

  lint-prettier:
    needs: build
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Restore yarn unplugged package cache
        uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        id: yarn-unplugged-package-cache-restore
        with:
          key: ${{ runner.os }}-yarn-unplugged-${{ github.ref_name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-unplugged-${{ github.ref_name }}-
            ${{ runner.os }}-yarn-unplugged-${{ github.head_ref }}-
            ${{ runner.os }}-yarn-unplugged-main
          path: |
            ./.yarn/unplugged
      - name: Restore Build cache
        id: cache-build-restore
        uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          key: ${{ runner.os }}-build-${{ github.ref_name }}-${{ hashFiles('./packages/*/*.tsbuildinfo') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.ref_name }}-
            ${{ runner.os }}-build-${{ github.head_ref }}-
            ${{ runner.os }}-build-main
          path: |
            ./packages/*/dist
            ./packages/*/*.tsbuildinfo
      - run: yarn format:ci

  lint-constraints:
    needs: build
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn constraints

  test-unit:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Restore yarn unplugged package cache
        uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        id: yarn-unplugged-package-cache-restore
        with:
          key: ${{ runner.os }}-yarn-unplugged-${{ github.ref_name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-unplugged-${{ github.ref_name }}-
            ${{ runner.os }}-yarn-unplugged-${{ github.head_ref }}-
            ${{ runner.os }}-yarn-unplugged-main
          path: |
            ./.yarn/unplugged
      - name: Restore Build cache
        id: cache-build-restore
        uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          key: ${{ runner.os }}-build-${{ github.ref_name }}-${{ hashFiles('./packages/*/*.tsbuildinfo') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.ref_name }}-
            ${{ runner.os }}-build-${{ github.head_ref }}-
            ${{ runner.os }}-build-main
          path: |
            ./packages/*/dist
            ./packages/*/*.tsbuildinfo
      - run: yarn test:unit
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          flags: unit
          os: ${{ matrix.os }}

  test-integration:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Restore yarn unplugged package cache
        uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        id: yarn-unplugged-package-cache-restore
        with:
          key: ${{ runner.os }}-yarn-unplugged-${{ github.ref_name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-unplugged-${{ github.ref_name }}-
            ${{ runner.os }}-yarn-unplugged-${{ github.head_ref }}-
            ${{ runner.os }}-yarn-unplugged-main
          path: |
            ./.yarn/unplugged
      - name: Restore Build cache
        id: cache-build-restore
        uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          key: ${{ runner.os }}-build-${{ github.ref_name }}-${{ hashFiles('./packages/*/*.tsbuildinfo') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.ref_name }}-
            ${{ runner.os }}-build-${{ github.head_ref }}-
            ${{ runner.os }}-build-main
          path: |
            ./packages/*/dist
            ./packages/*/*.tsbuildinfo
      - run: >-
          docker run
          --name google-pubsub-source
          --rm
          --detach
          --publish 8538:8538
          --env PUBSUB_PROJECT_ID=test-project-id
          gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
          gcloud beta emulators pubsub start --host-port=0.0.0.0:8538
      - run: yarn test:integration --runInBand --detectOpenHandles --forceExit
        env:
          PUBSUB_PROJECT_ID: test-project-id
          PUBSUB_EMULATOR_HOST: 127.0.0.1:8538
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          flags: integration
          os: ${{ matrix.os }}
